# title: Pneumothorax Classification
# description: We tested several different CNN models and compared their performance for pneumothorax classification. ????where is my title????
# remote_theme: pages-themes/cayman@v0.2.0
# plugins:
# - jekyll-remote-theme # add this line to the plugins list if you already have one


# Setup
title:        Try Try
tagline:      Use graph-based analysis to re-classify stocks in China A-share and to improve Markowitz portfolio optimization
baseurl:      /dynamic_stock_industry_classification
paginate:     1
locale:       "en"

# About/contact
author:       
  name:       Angela Wang
  url:        https://github.com/Angela-Wang111/Pneumothorax_classification

# Gems
gems:
  - jekyll-paginate
